### ISSUE TITLE
open multiple sublime text project plugin crushed 

### ISSUE THREAD

**Issue by dizengrong** [lintingbin2009/sublime_erl#6]
Exception in thread Thread-1601:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\Erl-AutoCompletion\util\data_cache.py", line 258, in run
    this.build_data()
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\Erl-AutoCompletion\util\data_cache.py", line 195, in build_data
    if self.get_folder_id(folder) != None:
  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\Erl-AutoCompletion\util\data_cache.py", line 227, in get_folder_id
    for (fid, pid) in self.db_cur.fetchall():
sqlite3.ProgrammingError: Recursive use of cursors not allowed.

**Comment by lintingbin** [comment]
Have fixed it in the new version.
